name: Lint Code Base

on:
  push:
    branches: [ "main" ]

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v6
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_AUTO_FIX: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: "main"
          VALIDATE_JAVASCRIPT_ESLINT: true
          FIX_JAVASCRIPT_ES: true

      - name: Check for changes
        id: git-check
        run: |
          echo "changed=$(git status --porcelain | grep '^[AM] ' | wc -l)" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.git-check.outputs.changed != '0'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: autofix lint errors"
          title: "chore: autofix lint errors"
          body: "This PR applies automatic lint fixes from Super Linter."
          branch: "autofix/lint-errors"
          base: main
          delete-branch: true
