name: Lint Code Base

on:
  push:
    branches: [ "main" ]

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v6
        env:
          LINTER_RULES_PATH: .github/linters/
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_AUTO_FIX: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: "main"
          VALIDATE_JAVASCRIPT_ESLINT: true
          FIX_JAVASCRIPT_ES: true
          FIX_JAVASCRIPT_PRETTIER: true
